### ISSUE TITLE
Joppa Road, TRO-22-03

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#10]
Bay was split into four instead of two (on two separate locations within the same Order draft). 

PCL was made aware of this on 13/05/22:

![Joppa Road, TRO-22-03](https://user-images.githubusercontent.com/109733089/180192783-51d0cd54-d6c6-47b9-a7fd-5d31b7e7e773.JPG)
![Joppa Road, TRO-22-03 2](https://user-images.githubusercontent.com/109733089/180192838-43d6ac68-4363-45dd-b873-6ca048c623e1.JPG)
.

**Comment by Djedouas** [comment]
Split tool has had big internal changes in the way it works.

Closing this issue.

Don't hesitate to open a new one if it appears again.
