### ISSUE TITLE
IK.  TRO/21/15 = 1220 & 1279 #31

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#100]
Hi,

It appears that the issue with map tile 1279 has reappeared as the map tile once more shows as revision number 6 (dated 12 September 2022 which would indicate it being part of TRO/21/15).

However, additionally it appears that when printing both a proposed (under TRO/21/18) and existing version they both show the same revision number:
![map tile 1279 existing](https://user-images.githubusercontent.com/109733089/223470442-f32616b8-06dc-4d2d-b5b4-728cc00749f3.JPG)
![map tile 1279 proposed](https://user-images.githubusercontent.com/109733089/223470500-a3065b62-6eab-4d66-b1e7-7256a2209261.JPG)

**Comment by Traffic-Orders** [comment]
Hi,

Could you please clarify what the "on hold" label means?

Many thanks

**Comment by Djedouas** [comment]
Hi,

This label means that the issue is not being addressed at the moment.

Currently, the reason is that we are waiting for budget renewal to spend time on issues

**Comment by Djedouas** [comment]
I will have a look at this issue ASAP, on Friday.

**Comment by Djedouas** [comment]
Hi,

This should be fixed now, can you confirm?

Thanks

**Comment by Traffic-Orders** [comment]
I can confirm that this matter has been resolved. Thank you
