### ISSUE TITLE
Mapping Update problems

### ISSUE THREAD

**Issue by greid12** [ProjectCentreLimited/TOMs#101]
Hi There,

I was performing a mapping update and had a similar problem to what we discussed on the phone a few weeks ago. I was trying to add the details from our new layer to the mapping update layer but the copy was not coming across and was getting met with python errors. This happens when we are copying into the attribute table. I remember this happening before but thought the problem was resolved> Let me know if anything has changed and if i need to try a different method once you have looked into this.

Thanks

**Comment by Djedouas** [comment]
Hi Gavin,

I prefer looking at this with screen sharing, it's easier.

I will email you.

**Comment by greid12** [comment]
All added to TRO-23-05, for making live

**Comment by Djedouas** [comment]
Done, can you confirm?

**Comment by greid12** [comment]
Apologies i had left one part out and it is now added via the staging account. I tried to do it on the live however we are missing this toolbar. Could you add it please?

![image](https://user-images.githubusercontent.com/116794639/227190544-56eab3f1-c0fc-40e2-b397-e2418fbd57f4.png)

**Comment by greid12** [comment]
they have been added 2 new features to TRO-23-05 on the mask update layer on the staging account

**Comment by Djedouas** [comment]
> Could you add it please?

I see that you have a WRITE (CAN CONFIRM) account, it means that we have to decide if:

1/ We give you a full ADMIN account (on live and staging versions), and only ADMIN accounts will be able to add mapping updates
2/ We add the toolbar to all the WRITE (CAN CONFIRM) accounts, which means that errors and mistakes could occur if someone with such an account plays with this toolbar

**Comment by Djedouas** [comment]
> they have been added 2 new features to TRO-23-05 on the mask update layer on the staging account

I transferred the features in the live version, can you confirm?

**Comment by greid12** [comment]
Can i get the full Admin access on my account, option 1

**Comment by Djedouas** [comment]
> Can i get the full Admin access on my account, option 1

OK done!
