### ISSUE TITLE
SL/CM Map tile 806 version number 4 query

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#103]
Hi 
map tile 806 was recently included in a made order (TRO/22/21) which comes into effect on 31/3/2023, when we produced the confirmed map tiles for 31/3/23 the system shows the version number as 5 but the existing map tile is shown as coming info effect on 4 May 2020 with a version number of 3? We do not have a record of any other Order affecting this map tile showing the missing version number 4.
Can you please confirm if there are any other changes to this map tile between 4 May 2020 and 31 March 2023 to help us establish the reason for the discrepancy in version numbers

**Comment by Traffic-Orders** [comment]
Sorry could you confirm all version numbers for map tile 806 and the effective dates please

**Comment by Traffic-Orders** [comment]
Hi I have discovered this was an old issue that was resolved, 806 had the 1st version number on 15/10/18 when the map based order was introduced, thereafter the same tile has been amended 4 times, now resulting in version 5 as follows
•	TRO/18/79 effective 11 March 2019 = Version 2 (intro DPPP o/s 38-46 Craighall Rd)
•	TRO/17/96 effective 23 April 2019 = Version 3 (intro DYLs at junctions of Craighall Rd & Grandville as well as Grandfield)
•	TRO/19/14 effective 4 May 2020 Should be Version 4 but was shown as Version 3 (intro DYL2KM on Craighall Rd, opposite junction of Grandfield) Darren Ryan previously arranged for the version number on TOMs to be corrected to 4.
•	TRO/22/21 effective 31 March 2023 = Version 5 (intro EV bays)
This can be closed, i have updated our parent order to reflect the same info

**Comment by Djedouas** [comment]
OK!

Don't hesitate to close the ticket yourself if you consider it done 😉
