### ISSUE TITLE
Copying from staging account to live account

### ISSUE THREAD

**Issue by greid12** [ProjectCentreLimited/TOMs#104]
There has been some problems highlighted in the live account from work which ws copied from the staging account. All looks good on the staging account so unsure why there are problems on the live account. Please can we set up a meeting to run through this and resolve it as a matter of urgency.

Thanks,

Gavin

**Comment by benoitdm-oslandia** [comment]
We will check our planing and find a date asap.

**Comment by Djedouas** [comment]
TRO-21-32

**Comment by Djedouas** [comment]
Done, can you confirm?

**Comment by SeanC75** [comment]
@greid12 can you add a comment on the faded lines issues please as I understand that this is an issue on the copy from staging to live?
