### ISSUE TITLE
IK. New restriction time required

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#106]
Hi,

I have a client who is proposing a loading bay which would be enforceable Monday - Friday between 7am and 9am. I have been unable to find this as an option on TOMs and was hoping for 'Mon - Fri, 7.00am and 9.00am' to be added by yourselves.

Many thanks in advance

**Comment by Djedouas** [comment]
Hi,

This should be ok now, can you confirm please?

Thanks

**Comment by Traffic-Orders** [comment]
Thank you!
