### ISSUE TITLE
TRO-23-01 - Make live

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#108]
Hi,

We have included the new information associated with TRO-23-01 in MappingUpdates and MappingUpdateMask in the LIVE system (i.e. not staging).

- Can you please make it live in the RestrictionInProposals?
- Can you please let us know how we can complete this step ourselves in the future so we do not have to raise a ticket? This would allow us to complete all the processes associated with this sort of task independently.

Many thanks,
Eduardo

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas,

Hope you are well.

Have you been able to make this live?

Thanks,
Eduardo

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas,

Hope you are well.

Do you have an update?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
The steps are SQL commands, so we must keep this on our side, until a dedicated development is made (for example, a button "make OS update live" with a popup to select the proposal).

This should be live now, can you confirm?

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas ,

It looks like the MappingUpdateMask has been made live but not the MappingUpdates (you can see on the example below the mask is shown but the new kerbs associated with TRO-23-01 are missing).
![image](https://user-images.githubusercontent.com/117166421/229479195-af882857-17b9-4287-ada4-fa37d19a7733.png)

Can you please make the MappingUpdates associated with TRO-23-01?

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

I think that @greid12 forgot to put 'Road' in the `DescGroup` field

![image](https://user-images.githubusercontent.com/34267385/229513424-86cc7e66-04c6-4713-9649-e80a3e22ed5e.png)

Without a DescGroup the lines won't show up.

I can add it if you want, for all MappingUpdates of TRO-23-01?

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas, we have now added the 'Road' in the DescGroup field and also added a couple more masks on MappingUpdateMask in TRO-23-01. 

Can you please make these live?

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

Some geometries that were added today were invalid.

@greid12 you have to be very careful to draw geometries without self-intersections, and with the right CRS (EPSG:27700), and with enough vertices.

I had to clean some geometries in mask layers, and I found some in label layers as well, leading to bad focusing on the map when selecting some proposals.

Can you check again please?
Thanks

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas 

One of the masks (~coordinates 327053.08,674431.40) has been added correctly.

However, the mask created to cover the island below (~coordinates 327384.1,674381.9) is not displayed.
![image](https://user-images.githubusercontent.com/117166421/229754514-216b1601-f893-4e6e-8e3a-721a9e760b74.png)

Can you please check why this mask is not being displayed?

Also, for my understanding, what do you mean by without self-intersections?

Thanks
Eduardo

**Comment by Djedouas** [comment]
> Also, for my understanding, what do you mean by without self-intersections?

a polygon or a line that crosses itself

![image](https://user-images.githubusercontent.com/34267385/229785475-ff3d3b81-d91f-4815-a71e-b4310a221d46.png)

**Comment by Djedouas** [comment]
Is it ok with this mask I drew?

If ok, I make this live.

![image](https://user-images.githubusercontent.com/34267385/229788591-532e58fc-7dbf-4b6f-ac27-f478d0c8c764.png)

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas - please make live

Eduardo

**Comment by Djedouas** [comment]
Done

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas
