### ISSUE TITLE
IK. Map tile printing error message

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#109]
I'm currently trying to print the proposed map tile for TRO/23/05, but the following error message appears instead:

![map tile printing](https://user-images.githubusercontent.com/109733089/228489255-60d82c95-31f5-42c5-aa29-b10c9f1a5658.JPG)

**Comment by EduardoMartin-Moral** [comment]
Hi,

I also get the same error message when printing - can you please help? 

Eduardo

**Comment by Djedouas** [comment]
@EduardoMartin-Moral `RestrictionsInProposals` and `MappingUpdates` were not synchronized...

I fixed the error, @Traffic-Orders please verify if the OS and mapping updates are ok.

**Comment by Traffic-Orders** [comment]
Thank you
