### ISSUE TITLE
Tiles Revision

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#110]
Hi,

As per @traffic-orders request, can you please revise the tiles revision numbers as per the attached spreadsheet?

Can you please give us an indicative completion date?

Regards,
Eduardo

[Copy of Tiles Assessment - TRO-21-03B.xlsx](https://github.com/ProjectCentreLimited/TOMs/files/11119481/Copy.of.Tiles.Assessment.-.TRO-21-03B.xlsx)

**Comment by Djedouas** [comment]
Hi,

Due to a full agenda, this can be achieved by the 21st of April, so I can still respond to other (urgent) TOMS issues.

Is it ok?

**Comment by Traffic-Orders** [comment]
Hi Jacky

Thank you for the update, please let us know once the amendments have been completed to the appropriate tile version numbers.

Thanks
Sharon

Sharon Lansdowne, Transport Officer – Traffic Regulations
•: ***@***.******@***.***>
•Network Management and Enforcement, Place, 4 East Market Street, Edinburgh, EH8 8BG
P  Please consider the environment before printing this email

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas - just checking if this is still planned to be completed by tomorrow?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
hi,

It should be fixed now, no need to logout and back in.

**Comment by Traffic-Orders** [comment]
Many thanks I have just checked on Toms and all are as requested 😊

Sharon
