### ISSUE TITLE
TRO-21-32 Make Live

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#114]
Hi,

We have included the new information associated with TRO-21-32 in MappingUpdates and MappingUpdateMask in the LIVE system, can you please make it live?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

Done, you can check :)

**Comment by EduardoMartin-Moral** [comment]
Check & closed - much appreciated @Djedouas
