### ISSUE TITLE
TRO-21-32 - Faded kerbs

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#115]
Hi, 

Can you please make the 'Stroke Width' of MappingUpdateMask so we do not see the faded kerbs as shown in the screenshot below?
We can make the change ourselve but for whatever reason when we log out and log back in this change is not saved.

![image](https://user-images.githubusercontent.com/117166421/231100752-8ad78969-d6f3-42a2-905d-ff8caca95be0.png)
![image](https://user-images.githubusercontent.com/117166421/231100846-6a2862f7-c8b4-42b7-b780-7befebc7f828.png)

Thanks
Eduardo

**Comment by Djedouas** [comment]
Hi,

Changing the stroke width is only a workaround.

The mask must be created such as its geometry actually masks the kerb.

When @greid12 creates the buffer, it should be a larger buffer.

It should be fixed by enlarging the mask geometry. I can explain the steps. Which proposal is this?

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas - Proposal TRO-21-32

**Comment by Djedouas** [comment]
Ok this is different than I thought.

These are large areas, and you are right, we need to adjust stoke width.

All parameters are reset at startup, and that's normal.

I did the change, can you confirm?

**Comment by EduardoMartin-Moral** [comment]
Looks good - thanks!
