### ISSUE TITLE
TRO 21-32 - Add time to bays

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#116]
Hi Jacky,

Can you please add the time: '**Mon-Sun 10:00am-1:00pm 7:00pm-midnight midnight-6:00am**' as an option for bay 'Time Period' feature?

![image](https://user-images.githubusercontent.com/117166421/231778187-27e15656-550d-4fad-89dd-745300653b32.png)

Appreciate if you can let me know an indicative time about when do you think you will be able to add this?

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
This should be available now (no need to logout)

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas
