### ISSUE TITLE
Can't print tiles

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#118]
Hi, 

We are trying to print the tiles associated with a proposal and we get the error below.

Can you please help?

![image](https://user-images.githubusercontent.com/117166421/232006696-7eb0bf8e-37b9-4118-a800-5e7f007260d2.png)

Thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

Which proposal is it?

**Comment by EduardoMartin-Moral** [comment]
TRO-21-32

**Comment by Djedouas** [comment]
Done

**Comment by Djedouas** [comment]
NB: the problem is that some restrictions are referenced in `RestrictionsInProposals` table, but are not present in the restriction table (i.e. a Bay that does not exist in the `Bay` table, but which is referenced in the proposal).

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas
