### ISSUE TITLE
Additional Time for Double Yellow Lines

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#119]
Hi,

Can you please add the option for 'no waiting time period'  Mon - Sun 18:30 to 06:30 for double yellow lines.
![image](https://user-images.githubusercontent.com/130752648/232534480-9085309c-fb6b-448d-9f73-50d63fdb5e6d.png)
 
Thanks

Stacey

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas - do you have an update on this?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
Added `Mon-Sun 6:30pm-6:30am`
