### ISSUE TITLE
TRO-23-07 Make Live

### ISSUE THREAD

**Issue by euanallen1** [ProjectCentreLimited/TOMs#120]
Hi,

We have included the new information associated with TRO-23-07 in MappingUpdates and MappingUpdateMask in the LIVE system, can you please make it live?

Thanks,
Euan

**Comment by Djedouas** [comment]
Done, please confirm.

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas - yes it worked.

I am trying to print the tile associated with the proposal (TRO-23-07) and get the error below:
![image](https://user-images.githubusercontent.com/117166421/234867546-301ad09f-09d9-489a-b945-aae2fa70ee6c.png)


We have not made any changes to the restrictions as part of this proposal and I do not know why is not letting me print the tile.
Can you please help?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
Fixed.

This comes from this kind of manipulation:

1. Mask updates are drawn, and I make them live by adding the modifications in the `RestrictionsInProposals` table.
2. Mask updates are deleted (and so, still in the `RestrictionsInProposals` table)

So I have to manually find the differences and resynchronize the tables.

**Comment by EduardoMartin-Moral** [comment]
Thanks - @Djedouas 

Once you make the Maskupdates live, I change the Descgroup of the lines that I do not want to show to 'Road End' and keep description of the other lines I want to show as 'Road'.

Then I print the resulting Tile.

Should I do this in a different way to streamline the process?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
As long as nobody deletes mask updates after I made these live, everything shoud be fine and this message should not appear.

If it's only changing a field (descgroup for instance) it's ok.

Let's be vigilant about that, so **if** it happens again I can dig deeper knowing that nobody deleted anything in mask updates after I make the mask updates live.
