### ISSUE TITLE
Leith Connections - Rogue Tiles

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#123]
Hi @djedouas,

We have been notified that 2no tiles (809 and 869) are included in proposal 'Leith Connections' when they shouldn't.
The Tiles that should be part of this proposal are 810, 869 and 928

I have checked MappingUpdates and MappingUpdatesMasks and no items associated with this proposal included in these layers extend to Tiles 809 and 868.

Can you please let me know why tiles 809 and 869 are being included in this proposal?

Can you please le me know how you check if any restrictions were edited/created associated with this proposal on the 'rogue tiles'?

Many thanks 
Eduardo

**Comment by Djedouas** [comment]
Hi,

A line (which is long and goes from tiles 809 to 810) has been changed:

![image](https://user-images.githubusercontent.com/34267385/234589696-2feeee61-be21-44eb-a217-fdb5cc4ac3d7.png)


![image](https://user-images.githubusercontent.com/34267385/234589355-3c05175c-3d62-4768-9db3-7844e31b8691.png)


---

Two lines on tiles 868 and 869 have been removed and redrawn exactly at the same place:

![2023-04-26_15-27](https://user-images.githubusercontent.com/34267385/234590281-6670d129-15d3-4b91-b2eb-ebe22abf3507.png)


---

The procedure to check this is completely inside the database administration, using SQL commands.

If you think that this could be useful, it needs a dedicated development to give administrators an interface on TOMS, please create an issue with the `enhancement` label explaining this need.

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas - can you please let me know when these changes were made in TOMS?

Thanks,
Eduardo

**Comment by Djedouas** [comment]
![](https://user-images.githubusercontent.com/34267385/234590281-6670d129-15d3-4b91-b2eb-ebe22abf3507.png)

2022-08-18 tim.hancock

---

![](https://user-images.githubusercontent.com/34267385/234589355-3c05175c-3d62-4768-9db3-7844e31b8691.png)
2023-02-14  admin (gavin being the only user with admin level)
