### ISSUE TITLE
TRO-22-24 Make Live

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#124]
Hello,

We have included the new information associated with TRO-22-24 in MappingUpdates and MappingUpdateMask in the LIVE system, can you please make it live?

Thanks

Stacey

**Comment by Djedouas** [comment]
Hello,

Done, can you confirm ? (no need to logout, just select another proposal and come back to TRO-22-24)

**Comment by EduardoMartin-Moral** [comment]
All good @Djedouas 
Thanks
