### ISSUE TITLE
TRO-21-32 Make Live

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#126]
Hello,

We have included new information associated with TRO-21-32 in MappingUpdates and MappingUpdateMask in the LIVE system, can you please make it live?

Thanks

Stacey

**Comment by Djedouas** [comment]
Hi,

Done ✅ 

Can you confirm?

Thanks

**Comment by smonteithskelton** [comment]
Hello,

Yes, can confirm this is complete.

Thank you
