### ISSUE TITLE
Allocation of Bays to CPZ Zones

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#127]
Hello,

Within the 'Zones' group in TOMS there is a layer for the CPZ which outlines the areas in magenta. 

Within the 'Restriction' group, we require all bays and lines within each of these areas to have the CPZ area within which they sit added to the attribute for each record. 

Is it possible for this to be done globally as there are a number that do not have a CPZ allocated? e.g bays outside the Assembly Rooms on George Street. 

Happy to have a call to discuss if required. 

Kind Regards

Stacey

**Comment by Djedouas** [comment]
Hello,

Currently, the CPZ should be automatically set when creating a new bay/line according to their location. (do you confirm?).

It's strange that some restrictions don't have a CPZ.

I understand that you are asking for a correction rather than a new feature in TOMS?

Regards

**Comment by smonteithskelton** [comment]
Hi Jacky,

Yes for new ones this field is populated automatically, so not sure how this has happened.

There are not a huge number but pretty much every zone has a few, I think so far there has only been one CPZ area where everything appears to be allocated.

Yes, this is a correction.

Thanks

Stacey

**Comment by Djedouas** [comment]
The restrictions have been updated all over the database (on past and current proposals):

- 4371 Lines updated with missing CPZ
- 1803 Bays updated with missing CPZ

Can you confirm?

Thanks

**Comment by smonteithskelton** [comment]
Hi Jacky,

I have went in and checked the ones I had noted and they appear to be updated.

Thanks very much for your help in resolving this.

Have a nice weekend.

Stacey

**Comment by Djedouas** [comment]
Have a nice weekend!

😄
