### ISSUE TITLE
TOMS New User

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#129]
Hi,

Can you please create a read only account for Joe Taylor [Joe.Taylor@edinburgh.gov.uk]?

Many thanks,
Eduardo

**Comment by benoitdm-oslandia** [comment]
done!

**Comment by EduardoMartin-Moral** [comment]
Hi @benoitdm-oslandia, Joe Taylor [[Joe.Taylor@edinburgh.gov.uk](mailto:Joe.Taylor@edinburgh.gov.uk)] has mentioned that he's note received the log in details.

Can these be send again?

Thanks
Eduardo

**Comment by benoitdm-oslandia** [comment]
Strange... but ok, I just send it gain.
