### ISSUE TITLE
TRO/22/03

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#13]
Drafted bay appearing as a line instead – can’t be selected/deleted on Hillside Street (reported to PCL on 18/05/22, but still not resolved):

![image](https://user-images.githubusercontent.com/109733089/180194277-b17164d2-5482-4527-8832-850e1940dff7.png)

**Comment by Djedouas** [comment]
This appears to be a drawing problem.

I examined the two bays (1 and 2 on the picture below) and they both have a segment going left. The yellow lines are the ones that are drawn.

![image](https://user-images.githubusercontent.com/34267385/196908698-bd063dc6-141f-404d-b6ea-6e9f0ad7c244.png)

But the bay in between only has one segment, so to be like the other 2 bays you have to edit the restrictoin and add 2 nodes, therefore adding the 2 segments:

![image](https://user-images.githubusercontent.com/34267385/196909355-9d0c5f62-e3b3-4217-8c4e-c5cb3b75fb1e.png)

**Comment by Djedouas** [comment]
Tell me if you prefer me to fix it.

**Comment by Traffic-Orders** [comment]
Hi,

Thanks for looking into this. If you could fix this, that would be much appreciated :)

**Comment by Djedouas** [comment]
Done ✅
