### ISSUE TITLE
New Account 

### ISSUE THREAD

**Issue by ninamason** [ProjectCentreLimited/TOMs#130]
Afternoon,

Looking to set up a user account for TOM's for the below:

Scott Robertson - scott.robertson@edinburgh.gov.uk
Stephen Brown  - stephen.brown@edinburgh.gov.uk
Aileen Naylor - Aileen.naylor@edinburgh.gov.uk
Gillian Dougherty - gillian.dougherty@edinburgh.gov.uk 

Let me know if you require any further information.

Thanks

**Comment by benoitdm-oslandia** [comment]
Hi,

what permission level should I set for these accounts?

Regards.

**Comment by ninamason** [comment]
Hi,

Could they please mirror Hannah McFarlane’s permissions ***@***.******@***.***>)

Many Thanks

Nina Mason / Senior Transactions Officer/ Customer Services and Information Technology (Parking Services) / Corporate Services / City of Edinburgh Council / Waverley Court Level 3/3, 4 East Market Street, Edinburgh, EH8 8BG
***@***.***

**Comment by benoitdm-oslandia** [comment]
done!

**Comment by ninamason** [comment]
Good Morning,

Thank you for this.

Would it be possible to resend ***@***.******@***.***> the email please as he has not received the email.

Many Thanks

Nina Mason / Senior Transactions Officer/ Customer Services and Information Technology (Parking Services) / Corporate Services / City of Edinburgh Council / Waverley Court Level 3/3, 4 East Market Street, Edinburgh, EH8 8BG
***@***.***

**Comment by ninamason** [comment]
Morning,

Can Scott Robertson’s log in please be resent as he has deleted the email.

Thanks

Nina Mason / Senior Transactions Officer/ Customer Services and Information Technology (Parking Services) / Corporate Services / City of Edinburgh Council / Waverley Court Level 3/3, 4 East Market Street, Edinburgh, EH8 8BG
***@***.***
