### ISSUE TITLE
IK - Unable to print proposal TRO-23-21 map tiles

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#131]
Hi,

I'm trying to print map tiles, but the following notification shows up instead:
 ![Capture](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/60bf2620-7640-498e-b01f-d625c352792f)

**Comment by Djedouas** [comment]
Hi,

Fixed today.

No need to log out.
