### ISSUE TITLE
IK. Map tile removal request from proposal TRO/21/23

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#132]
Hi,

Could the following map tiles please be removed (the changes made on them are no longer required as part of the proposal) from TRO/21/23:
1344
1810
1917
1922
1944
2038
2048
2407

Many thanks in advance

**Comment by Djedouas** [comment]
Hi,

I removed the changes that were present on the mentioned tiles.

However, tiles 1344 and 2407 were already not present when printing TRO/21/23.

Can you confirm (no need to logout)?

Thanks

**Comment by Djedouas** [comment]
Hi,

Is it ok to close this issue?

Thanks
