### ISSUE TITLE
IK. TRO/23/21 map tile 2220

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#133]
Hi,

Looking for some clarification regarding map tile 2220, as we're unsure why this was included in the proposal? As far as we can see no changes were made to this?

Many thanks

Isabelle

**Comment by Djedouas** [comment]
Hi,

This line has been removed and re-added

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/ff5b2668-ace6-4f31-a223-5fe1f0371491)

That is to say that it is probably a mistake (the removal) and that the line has been drawn again (so for TOMS it's a new restriction).

---

But there is also these mapping updates (I highlighted them in red and gray here)

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/fc378ae3-6649-4de6-a7eb-df7c7b38eeb3)
