### ISSUE TITLE
DY - New Time Period Request

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#134]
Hi,

Can you please add an option for "Mon - Fri 07.00am - 08.30am" to the Time Periods field in Bays - Feature Attributes.

The proposal I am working on (TRO/23/19 & Geometry ID B_0082247) needs the new Loading Bay to have these times of operation and I do not see this as an existing option.

**Comment by Djedouas** [comment]
Hi,

Done today, added `Mon-Fri 7.00am-8.30am`
