### ISSUE TITLE
DY. Unable to print proposed map tiles

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#135]
Hi

When I attempt to print the proposed map tiles for TRO/23/19 I get the following error message.

"getProposalTileDictionaryForDate failed with RestrictionID: 64319408-7818-4cba-afba-e4abe0d2f705"

![image](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/d94e57e7-3d82-4afb-bcb7-31043ba1c33d)

**Comment by Djedouas** [comment]
Hi,

This error occurs when a restriction has not been correctly deleted.

Have you had problems during this proposal, when deleting restriction(s)?

I updated the database so that the deletion is now propagated.

You should be able to print now.

**Comment by Traffic-Orders** [comment]
Hi,

Yes, they wee multiple occasions when I would delete, edit or add a restriction where either nothing happened or it reverted back. Thanks I will try printing again.

**Comment by Traffic-Orders** [comment]
Just to confirm I was able to print
