### ISSUE TITLE
Make TRO/22/25 Live

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#137]
Hello,

We have included new information associated with TRO/22/25 in MappingUpdates and MappingUpdateMask in the LIVE system, can you please make it live?

Any queries please just let me know. 

Thanks

Stacey

**Comment by Djedouas** [comment]
Hi,

I tested a new tool to make MappingUpdates and MappingUpdateMask live.

Do you see your changes now?

Thanks

Jacky

**Comment by smonteithskelton** [comment]
Hi Jacky,

I have had a look and the proposal doesn't now seem to be showing in either layer?

It is also not showing on the map - the red scribble on the screenshot below is what I would be expecting to see:

***@***.***

Thanks

Stacey

**Comment by Djedouas** [comment]
Hi Stacey,

Please write your answer on GitHub, where it is very easy to send snapshots as well (just drag and drop in the message).

Thanks

**Comment by smonteithskelton** [comment]
Hi Jacky,

I have had a look and the proposal doesn't now seem to be showing in either layer?

![Capture](https://github.com/ProjectCentreLimited/TOMs/assets/130752648/f541d188-7901-44dc-a4d8-b8d47b6f964c)

**Comment by Djedouas** [comment]
Done.

But I think that there is a mapping update mask missing (it does not exist, so I can't make it live)

**Comment by smonteithskelton** [comment]
Can see that now Jacky thanks. 

I have added the mask to the mapping update layer again - can you see it?  

Stacey

**Comment by Djedouas** [comment]
Yes, I tested the new button for admin users (I see you have admin rights), and it worked.

So you can test it too.

When you add mapping updates / masks, you can then click on this button to make them live (i.e. synchronize all the data with the new mapping updates) 

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/80b2f628-ab1b-4ebc-aca3-d43b1306f579)

You need to be on the right proposal.

Jacky

**Comment by smonteithskelton** [comment]
That's great Jacky thank you.

 TRO/22/25 is now complete.
