### ISSUE TITLE
Resend Users log in

### ISSUE THREAD

**Issue by ninamason** [ProjectCentreLimited/TOMs#139]
Good Morning,

can you please resend Scott Robertson's (scott.robertson@edinburgh.gov.uk) log in details to him as he seems to have deleted the email.

Many Thanks

**Comment by Djedouas** [comment]
Hi,

The welcome email has been resent.

Is it ok?

**Comment by ninamason** [comment]
Hi,

Scott has not received this email.

Thanks

**Comment by Djedouas** [comment]
Second attempt, and this time?

**Comment by ninamason** [comment]
Hi,

Apologies, the email address should Scott.s.robertson@edinburgh.gov.uk 

Sorry for this.

Nina

**Comment by Djedouas** [comment]
Hi,

All right, I've done the modification, is it ok?
