### ISSUE TITLE
IK, Unable to create proposals

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#141]
Hi,
I'm trying to create a proposal and for some reason it's showing an effective date - however, according to colleagues this shouldn't be something worry about.: 
![MicrosoftTeams-image (1)](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/de6a11d7-832a-4615-b767-fbbf9ff39291)
I therefore clicked OK, but I keep on getting the following error message now:

![MicrosoftTeams-image (2)](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/e88066ca-5148-4552-b380-e6b20d2c8a20)

Could this please be looked into?

Many thanks

**Comment by Djedouas** [comment]
Hi,

That's right, the problem is unrelated with the dates.

It seems that there has been a regression recently, and proposal creation is broken.

Looking into it.

**Comment by Djedouas** [comment]
Fixed, can you confirm?

**Comment by Traffic-Orders** [comment]
Hi,

I can confirm that I was able to create a proposal - thank you :)
