### ISSUE TITLE
IK - labels not showing on proposed map tiles

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#142]
Hi,

Hope you can help - several members of the team have been experiencing issues when printing proposed map tiles; the labels aren't showing (please see the below screenshots for more detail). So far today I've tried printing the map tiles for an Order four times. I hope you can appreciate that this is a time consuming exercise that is now impacting our workload. 

Many thanks

![Proposed map tile](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/00af1343-04e7-4c55-a4ec-357d0aced336)
![Existing map tile](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/2fb2504f-d989-4fe3-9caa-f7df8cfd3915)

**Comment by Djedouas** [comment]
Hi,

I can see no label on the first screenshot, and 3 labels on the second screenshot.

Also the dates and the status are different between the 2.

Can you explain in more details how those 2 screenshots were taken please? Thanks

**Comment by Traffic-Orders** [comment]
Hi,

Please be advised that the issue is that there are no labels showing on the proposed map tile (we are proposing to make changes on the on-street restrictions). The labels are currently only showing on the confirmed map tile (which shows the restrictions that are currently covered under the Order and therefore on street).

Please be advised that the dates of the map tiles differ as one is a proposal and the other a confirmed map tile - this is normal.

Hope this helps :)

**Comment by Djedouas** [comment]
Which proposal do you select for the "proposed" version of the printed tile?

**Comment by Traffic-Orders** [comment]
This is proposal TRO/22/25 - however, it's been happening with other proposals as well.

**Comment by Djedouas** [comment]
Hi,

Do you have an example of a proposal where it works? labels on the confirmed map tile and labels on the proposal map tile?

**Comment by Djedouas** [comment]
OK, I don't need an answer to my previous question, I found the reason.

TOMS does not print the labels, if the labels are not shown on the map because of an insufficient zoom for example.  
So before hitting the last print button when the tiles are chosen, be careful to have the map correctly zoomed in and the labels visible.

I am looking for a way to fix it, this is an absurd behavior.

**Comment by Djedouas** [comment]
Fixed with c3154ff

Can you confirm? (need a log out)

It is in fact (for what I found) independent of the status (confirmed or proposed).

**Comment by Traffic-Orders** [comment]
Thank you :)
