### ISSUE TITLE
DY - Add Street name Barnie Terrace

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#144]
Hi

Can you please add Barnie Terrace in Portobello as a street so that it can be searched for and appears on the map tiles? There are new DPPPs included in proposal TRO/22/18 for this location.

![image](https://github.com/ProjectCentreLimited/TOMs/assets/109733089/799739b8-bf07-4b2a-8bf8-f2558cf34f9c)

[TRO_22_18_1408.pdf](https://github.com/ProjectCentreLimited/TOMs/files/12037945/TRO_22_18_1408.pdf)
[CurrentRestrictions_(2023Jul12)_1408.pdf](https://github.com/ProjectCentreLimited/TOMs/files/12037955/CurrentRestrictions_.2023Jul12._1408.pdf)

**Comment by Djedouas** [comment]
I got the path from https://www.openstreetmap.org/way/250800855

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/cdf0b2c7-63b1-42f7-a1ff-f35526eb6b59)


The street is available now, but I didin't find the Unique Street Rerefence Number (USRN), nor the Elementary Street Unit ID (ESUID).  
I don't think those are used in TOMs however.

Please confirm 😃 

Thanks

**Comment by Traffic-Orders** [comment]
Hi

I can see the street name on the map and search for it so that should allow us to progress this proposed TRO.

Thank you
