### ISSUE TITLE
Exporting Bays and Lines

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#145]
Hello,

I am looking for some assistance on exporting bays and lines into a CAD friendly format (.dxf/.dwg etc) whilst showing their associated colour as per TOMS i.e pink for permit holder bay or orange for DYL. I am looking to do this for a specific area, at a specific date. Is this something that is possible?

Thanks in advance for any help with this!

Stacey

**Comment by Djedouas** [comment]
Hello,

You have an administrator account, so you can try QGIS menu to export a project to DXF:

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/1b6cd3b6-0080-442b-a308-ffc8973d609d)

See QGIS documentation here for the available options (especially the checkbox `Export features intersecting the current map extent`):

https://docs.qgis.org/3.28/en/docs/user_manual/managing_data_source/create_layers.html#create-dxf-files

---

Don't hesitate to ask any further question 😉

**Comment by Djedouas** [comment]
Another resource: https://www.qgis.ch/fr/projets/export-dxf

**Comment by Djedouas** [comment]
You should probably try the "Symbol layer symbology" setting

**Comment by smonteithskelton** [comment]
Thanks, using the above I have tried exporting the 'Bays' Layer using these but when I open the DXF it is only displaying lines all the same colour. It must be due to the formatting in TOMS making it line based when it pulls off. When I am pulling the 'Lines' layer it is also pulling off all lines but in the same colour, not the colours as determined within the layer in TOMS. Thanks again for your help with this.

**Comment by Djedouas** [comment]
Yes, the symbology is quite a problem to move from a software to another...

QGIS being easy to access for everyone, maybe you can share in another format (shapefile, geopackage...), and export the layer style as well (in QGIS `.qml` file type).

**Comment by smonteithskelton** [comment]
Thank you - I'll give this a go. 

Stacey
