### ISSUE TITLE
Make TRO-23-14 Live

### ISSUE THREAD

**Issue by smonteithskelton** [ProjectCentreLimited/TOMs#147]
Hello,

We have included new information associated with TRO-23-14 in MappingUpdates and MappingUpdateMask in the LIVE system, can you please make it live?

Any queries please just let me know.

Thanks

Stacey

**Comment by Djedouas** [comment]
Hi Stacey,

As an admin user, you should be able now to do it yourself, with the new button I added for admins only.

Can you test it please?

1. go in the proposal
2. hit this button ![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/1782bc97-179e-409a-99ca-0009e8b213b6)

Thanks

**Comment by smonteithskelton** [comment]
Hello,

I have done that and it has brought in the new kerblines, which is great. However it has also deleted quite a considerable bit of background mapping that was not drawn/highlighted in the changes? Any ideas on why this has happened/ how we can rectify? 

This has happened at all 4 locations under this proposal. 

Blue outline is the new kerbline, red is missing mapping.

![image](https://github.com/ProjectCentreLimited/TOMs/assets/130752648/5257524a-c9f4-403c-b42e-1c30ea460b16)

**Comment by Djedouas** [comment]
It appears that those masks were drawn by someone who did it on purpose, and were in the "waiting list" to be made live.

Here they are:

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/aaa84d93-cd42-41b8-b157-6accde32ea57)

**Comment by Djedouas** [comment]
We can remove them if needed

**Comment by smonteithskelton** [comment]
Yes please remove those grey masks. It should only have been the outer kerbline that was masked, not sure how those shapes have been created. Thanks

**Comment by Djedouas** [comment]
Done!

No need to logout.

You will be able to test it again next time :)

**Comment by smonteithskelton** [comment]
Thanks, I will reload the files and try the masking again.

Stacey

**Comment by smonteithskelton** [comment]
Hello,

Have reloaded the mask files and it appears to have done the job this time.

Thanks for your help with this.

Stacey
