### ISSUE TITLE
TRO-19-35

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#15]
The TRO Proposal for car club bays at a few locations included a request to replace part of a shared use bay with a car club bay on Warriston Rd held in map tile 1160. This was drafted in TOMs some time ago with part of an existing shared use bay being replaced with the proposed car club bay. However the car club bay at this location has not to be taken forward so i have today deleted the proposed car club bay and reinstated the original length of shared use bay. However, whilst technically there is now no change to this map tile, TOMs is still including the tile 1160 in the proposal. Please remove map tile 1160 from the proposal TRO-19-35 as the version number of this tile should not be revised when this Order is made because no changes have been made to the actual Order. See snippet below for info 
![image](https://user-images.githubusercontent.com/109733089/180924857-20048be8-28b6-4a56-9163-9f756f53d18d.png)

**Comment by Djedouas** [comment]
Ok, done!
