### ISSUE TITLE
Additional times for Waiting and Loading Restrictions

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#164]
Hi,

Can the following timescales be added to the Waiting and Loading Restrictions, 
This will be required for us to complete TRO-21-32 which is expected to be made by the Council this week.

- Mon – Sun 7:00am – 9:00am, 11:00am – 2:00pm,  3:00pm-11:00pm
- Mon – Sun 12:30pm – 09:30am
- Mon – Sun 6:00am to 10:00am and 1:00pm – 7:00pm

Thanks
Eduardo

**Comment by Djedouas** [comment]
Done
