### ISSUE TITLE
Appyway (Freya) - Issues with login

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#167]
Hi,

Freya (freya.markham@appyway.com) from Appyway is experiencing issues when trying to log in.
She gets the following message:
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/c7dffb9c-4ab1-4f5d-a92e-c12f8e23d04d)

Can this be resolved with urgency, Appyway are aiming to start importing the data from Monday and are keen to be able to compare what they are importing to TOMS.
Thanks
Eduardo

**Comment by benoitdm-oslandia** [comment]
Account is still active. I have re-sent the invitation email.
