### ISSUE TITLE
TOMs toolbar

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#170]
Hi

My colleague Stephanie Lennie has access to TOMs however she does not appear to have the TOMs measuring toolbar.  We have checked the 'view' and 'toolbar' settings and whilst the 'TOMs toolbar' is selected the tools such as 'create construction line', 'edit restriction' etc are missing.  Can this please be resolved ASAP as all Traffic Orders team members need access to these tools.

Thanks

**Comment by Djedouas** [comment]
Hi,

Stephanie Lennie has a read only account.

Should I upgrade to write_no_confirm ?

**Comment by Traffic-Orders** [comment]
Hi, yes Stephanie Lennie, who has recently joined the Traffic Orders team, should have the same settings as other Traffic Orders team members, thank you

**Comment by Djedouas** [comment]
I don't have a record of who is in Traffic Orders team, so I can't compare.

I've upgraded her account to a write_no_confirm level.

Is it OK? She has to log out and log back in.

**Comment by Traffic-Orders** [comment]
Hi, thanks for making the change. Stephanie now has access to the toolbar.

**Comment by Djedouas** [comment]
Great!

Closing
