### ISSUE TITLE
Grant access to STAGING

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#171]
Hi - can you please grant access to the Staging environment (read only) to:

Holly Robertson – [holly.robertson@edinburgh.gov.uk](mailto:holly.robertson@edinburgh.gov.uk) (should already have access)
Sharon Lansdowne – [Sharon.lansdowne@edinburgh.gov.uk](mailto:Sharon.lansdowne@edinburgh.gov.uk)
Charlotte Moore – [charlotte.moore@edinburgh.gov.uk](mailto:charlotte.moore@edinburgh.gov.uk)
Darren Young – [darren.young@edinburgh.gov.uk](mailto:darren.young@edinburgh.gov.uk)
Isabelle Knops – [Isabelle.knops@edinburgh.gov.uk](mailto:Isabelle.knops@edinburgh.gov.uk)
Stephanie Lennie - [stephanie.lennie@edinburgh.gov.uk](mailto:stephanie.lennie@edinburgh.gov.uk)
Andrew MacKay – [a.mackay@edinburgh.gov.uk](mailto:a.mackay@edinburgh.gov.uk)

Thanks
Eduardo

**Comment by Djedouas** [comment]
Hi,

Holly Robertson and Darren Young already have access with write (without confirm) level. Should I downgrade the level to read only?

Sharon Lansdowne: done with read only  
Charlotte Moore: done with read only  
Isabelle Knops: done with read only  
Stephanie Lennie: done with read only  
Andrew MacKay: done with read only  

Thanks  
Jacky

**Comment by EduardoMartin-Moral** [comment]
Morning Jacky - yes, please

Eduardo

**Comment by Djedouas** [comment]
Done
