### ISSUE TITLE
CEC Issue confirming map tiles

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#173]
Hi

CEC are having issues this morning in confirming map tiles and are receiving the following error message.  
They need to confirm these map tiles today (for 23/25 & 23/05) – CEC needs this done no later than 2pm or they will need to pull the adverts that will likely incur costs.

The error message they are getting is:
 
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/1c16870a-4d24-4296-8f9d-0266d1df648a)

They have tried rebooting and logging in and got the same error as above initially and now it just seems stuck – see screen shot below (stuck at 12%):
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/bbee9f97-bb01-4a1a-91d2-2cefa25cb5aa)

 
Can you please advise on the resolution of this issue as a matter of urgency?

**Comment by EduardoMartin-Moral** [comment]
Hi - wondering if you have an update on this issue?

Thanks

**Comment by Djedouas** [comment]
Hi, the issue should be resolved. Please confirm.

Thanks

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas - yes it has been resolved.

Thanks all for the quick resolution, much appreciated.
