### ISSUE TITLE
TRO/17/92A - general issue

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#18]
Hi,

There appears to be an issue with a proposal that was drafted by myself (Isabelle Knops) - my colleagues cannot see any of the restrictions I drew. 

Hope this can be looked into.

Many thanks

![Isabelle Knops TRO-17-92A](https://user-images.githubusercontent.com/109733089/191732710-47b7aa64-21b7-4b22-87a5-b56b65164cb5.JPG)
![Sharon Lansdowne TRO-17-92A](https://user-images.githubusercontent.com/109733089/191733004-11e99046-824a-4316-90cc-510ec8af0f96.jpg)
<img width="957" alt="Holly Robertson TRO-17-92A" src="https://user-images.githubusercontent.com/109733089/191733148-4f764ccc-7a40-4f78-9ee4-7595dbd1c041.PNG">

**Comment by Djedouas** [comment]
This issue occurred before switching to the Oslandia/AWS version of TOMs.

What is the status today?

**Comment by Traffic-Orders** [comment]
Hi,

this is still an issue, but now I too (Isabelle Knops) am no longer able to see the restrictions I drafted, which is an issue:
![17-92A](https://user-images.githubusercontent.com/109733089/196747560-87dc8104-ce55-4d35-9423-c35aff539022.JPG)

**Comment by Djedouas** [comment]
Can you see the restriction when TOMs panel is not activated at all? 

Deselect TOMs icon:

![image](https://user-images.githubusercontent.com/34267385/196750573-dc14a448-a6f0-4b99-a087-c56daa8cf78a.png)

And go to this location to see what appears. Normally there is no filter so if you can't see the restriction, it has not been migrated to this version and need to be created again.

**Comment by Traffic-Orders** [comment]
Did as you said, and I could see the restrictions:
![17-92A 2](https://user-images.githubusercontent.com/109733089/196900306-add4b887-529f-40d9-89fb-540cc04675a7.JPG)

But they disappeared again once the toolbar was activated.

Many thanks

**Comment by Djedouas** [comment]
Investigating...

**Comment by Djedouas** [comment]
That was a *tricky* one!

Your very **first** screen capture shows TRO **/** 17 **/** 92A

![image](https://user-images.githubusercontent.com/34267385/197788973-d8d6f559-e809-4ea6-b008-4fae19c5b38c.png)

and **every** other screen captures show TRO **-** 17 **-** 92A

![image](https://user-images.githubusercontent.com/34267385/197789481-6514c719-0d41-4802-8c2a-7dcedefcaf98.png)


not easy to find! had to dig deep into the code, not finding any bug... 😄

**Comment by Djedouas** [comment]
I can try to merge the 2 proposals, but it implies manual tuning in the database.

As an example, they have different open dates and notes.

![image](https://user-images.githubusercontent.com/34267385/197791571-1be8a0c6-9930-435f-ae35-fd88545a8264.png)

**Comment by Traffic-Orders** [comment]
Thank you for getting to the bottom of this! Much appreciated.
