### ISSUE TITLE
Permissions for Holly Robertson

### ISSUE THREAD

**Issue by SeanC75** [ProjectCentreLimited/TOMs#27]
Can permissions for Holly Robertson's profile be changed from read only to write and read please?

**Comment by Djedouas** [comment]
This is already the case.

The associated profile for Holly Robertson is `write_no_confirm_operator`

([see reference role table here](https://github.com/ProjectCentreLimited/TOMs/blob/develop/script/aws/DEPLOY.md#user-elevation))

**Comment by Djedouas** [comment]
Is everything ok here?

**Comment by Djedouas** [comment]
@SeanC75 have you checked if the problem is still happening?

**Comment by SeanC75** [comment]
Closed as no info from user so assuming working as expected
