### ISSUE TITLE
Map tile saving

### ISSUE THREAD

**Issue by SeanC75** [ProjectCentreLimited/TOMs#28]
When the users create a map tile and save it, the location that is specified to save to, when accessing that file location the files are not visible. 

Could you please confirm the process for retrieving printed map tiles?

**Comment by Djedouas** [comment]
The map tile (PDF) has to be saved in the home folder (see picture 1).

Then the user can access this folder with AWS button in the top left-hand corner (see picture 2), wich can be then downloaded with a click on the file.


**Picture 1**

![image](https://user-images.githubusercontent.com/34267385/194553129-975f9f7e-cb32-4365-a7b1-7634d288ea3a.png)


**Picture 2**

![2022-10-07_14-22](https://user-images.githubusercontent.com/34267385/194552692-6d7d326f-4c01-4605-b83c-c610e2cb4ec6.png)

**Comment by SeanC75** [comment]
Thanks for the info
