### ISSUE TITLE
Read only users are unable to access geometry data

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#29]
Read only users are unable to access geometry data for parking places and restrictions. This data is accessed regularly and needs to be available to all users.
![TOMs](https://user-images.githubusercontent.com/109733089/195294176-e76a4a25-2001-469c-9f29-caa46e70c1cc.jpg)

**Comment by Djedouas** [comment]
I see the problem. I will fix it ASAP.

**Comment by Djedouas** [comment]
Log-out and log back in for the fix to take effect.
