### ISSUE TITLE
Error message when accepting proposal for TRO-22-04

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#34]
Hi we are making TRO/22/04 today 19/10/22 and with a coming into effect date of 05/12/2022 however when attempting to accept the proposal on TOMs this morning i continued to get the below error message. This needs accepted today with the coming into effect date as per above so that we can prepare the necessary map tiles for public inspection when the Order is advertised on Friday 21/10/22. As such please arrange for the error to be corrected or so that i can accept it this morning or at the very least have the file accepted today so that we can prepare the necessary docs for the web etc tomorrow
![image](https://user-images.githubusercontent.com/109733089/196632912-56917c11-90b1-4e9d-a285-0ef5d932eb45.png)
![image](https://user-images.githubusercontent.com/109733089/196632944-7cbc2f54-d0a8-4a50-9e87-d39a501c17d2.png)

**Comment by Djedouas** [comment]
Hi,

Has it happened before or is it the first time an order is being accepted on this TOMs version?

**Comment by Traffic-Orders** [comment]
This is the first time i have tried to accept since the new version of the system was released. before that i could accept proposals

**Comment by Djedouas** [comment]
I made some fixes.

You can log out, and log back in, and try again, please.

**Comment by Traffic-Orders** [comment]
My session timed out so i attempted to initiate the system but the system shows connecting then the system just hangs see below snippet
![image](https://user-images.githubusercontent.com/109733089/196668467-7339f16a-303a-4e84-ac57-1aad90e36a56.png)

**Comment by Djedouas** [comment]
This seems like a long loading time. Is it working now?

**Comment by SeanC75** [comment]
The user got the following error message: “ERROR: new row violates row-level security policy for table “proposals””

**Comment by Djedouas** [comment]
Good news, that means we fixed the first bug 😄 

Thanks for the update, I'll keep looking.

**Comment by Djedouas** [comment]
@SeanC75 @Traffic-Orders who is the user?

**Comment by Traffic-Orders** [comment]
Hi, the user is Sharon Lansdowne

**Comment by SeanC75** [comment]
The error logged today was from Gavin Reid

**Comment by Djedouas** [comment]
OK the problem should be fixed @SeanC75 @Traffic-Orders 

A low-level security policy was blocking all `write_confirm_operator` users to confirm orders.

Signing out and back in should resolve the problem now.

**Comment by Traffic-Orders** [comment]
Hi thank you for your help, i have successfully accepted the proposal under TRO/22/04
