### ISSUE TITLE
No access available to TOMs

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#37]
Constantly getting message no streaming resources available, TRO team have requested we are given priority via PCL, awaiting feedback. Isabelle and I are both experiencing this problem just now
![image](https://user-images.githubusercontent.com/109733089/197772355-40f8b8bb-dec8-419f-a268-90af15a2c61d.png)

**Comment by Djedouas** [comment]
Thanks for the info, this issue is already being followed in #35
