### ISSUE TITLE
TOMs error - TRO/17/92A

### ISSUE THREAD

**Issue by SeanC75** [ProjectCentreLimited/TOMs#43]
Also, not sure if you might be able to assist with the following, I raised a while ago. Part of the yellow lines drafted won’t snap onto the road and appear on the pavement instead. With the new version of TOMs being live now, I gave drafting this another go, but the same issue occurs:
 
 
![image](https://user-images.githubusercontent.com/115094257/199214575-945b18a2-fb0a-43c3-a45c-65bef14e365a.png)

**Comment by Djedouas** [comment]
Lines that are falling on the pavement have a wrong *direction to road centerline* value 

![image](https://user-images.githubusercontent.com/34267385/199457360-2548177e-7a99-4ddd-a9d0-41c7bb32b785.png)

Just change that value (try to add 90° or 180°)

**Comment by Djedouas** [comment]
Is this ok?

**Comment by SeanC75** [comment]
Closed as a dupe
