### ISSUE TITLE
TOMS not showing changes made

### ISSUE THREAD

**Issue by suhaibahmad97** [ProjectCentreLimited/TOMs#44]
Despite saving restrictions which are being edited, these changes are not being shown after a few hours.

 The TOMS account says WRITE LIVE which means I am authorised to make changes. 

My manager had to use his account to redo the changes that I had originally done as it showed uncompleted on his account.

Why are the changes being made not being saved on my account ?

Kind regards.

**Comment by Djedouas** [comment]
Hi,

The drawings are immediately up-to-date after saving, visible to everyone.

There is no distinction between WRITE LIVE accounts, does your manager have a WRITE LIVE account also? If yes, both of you have the same permissions.

What you describe should not have happened.

I need you to reproduce the issue, and describe exactly all steps for me to test it. Thanks.

**Comment by SeanC75** [comment]
@suhaibahmad97 Please review the previous comment and detail the recreation steps

**Comment by suhaibahmad97** [comment]
> @suhaibahmad97 Please review the previous comment and detail the recreation steps

I am unable to recreate this issue at this moment. The changes being made seem to remain.
It is difficult to see what was not saved as my manager has made these changes. 
If this does occur again, I will create a new issue and detail the recreation steps.
Thank you.
