### ISSUE TITLE
Client Logo not showing when printing tiles

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#45]
I am printing tiles via TOMS and where it is supposed to appear the CEC logo I only see a red cross.
![image](https://user-images.githubusercontent.com/117166421/199216511-6aa27462-0216-4c0d-b0f3-e1a9afecb2c7.png)

**Comment by SeanC75** [comment]
@EduardoMartin-Moral Do you have the image as either a png or svg? This was already requested by Olsandia.

**Comment by EduardoMartin-Moral** [comment]
Hi @SeanC75, Gavin Reid provided this information. I have forwarded you the email. Thanks.

**Comment by SeanC75** [comment]
![edinburgh-council](https://user-images.githubusercontent.com/115094257/199451383-1b19d1f0-7b7f-4c65-a0fd-322d567effcb.png)

**Comment by SeanC75** [comment]
@benoitdm-oslandia Attached new file provided from PCL

**Comment by benoitdm-oslandia** [comment]
hi @EduardoMartin-Moral, the file format is not the good one. We are looking for the original vector format (SVG). What you sent us is a raster image (PNG). Can you send us the SVG version of the file please ?

**Comment by EduardoMartin-Moral** [comment]
Hi @SeanC75 ,

Would the attach work?
![edinburgh-city-council](https://user-images.githubusercontent.com/117166421/199475520-3a9cccc2-47a7-4863-8b87-55059872713d.svg)

**Comment by benoitdm-oslandia** [comment]
@Djedouas I uploaded the image onto the server!
