### ISSUE TITLE
No access to TOMS 

### ISSUE THREAD

**Issue by euanallen1** [ProjectCentreLimited/TOMs#53]
I have lost access to TOMS mid-session. I have attempted to reload several times and cannot yet access it. 
Please find attached some of the error messages received whilst trying to load TOMS.

Can this be resolved?

![Capture (TOMS 1)](https://user-images.githubusercontent.com/117725519/200541630-886107bf-34d7-4b45-bce0-5e0d8e3662c2.PNG)
![Capture (TOMS 2)](https://user-images.githubusercontent.com/117725519/200541633-c3040071-f450-4e43-8625-b0ba5a596590.PNG)

**Comment by Djedouas** [comment]
Please see my comment in [#35](https://github.com/ProjectCentreLimited/TOMs/issues/35#issuecomment-1290479368)
