### ISSUE TITLE
Can't access TOMS

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#55]
Hi,

I have been working on TOMS this morning and now I can't access the system, getting the message below - Can you please help?
Thanks

![image](https://user-images.githubusercontent.com/117166421/200560684-8c9be4c8-2a46-4c0c-872a-0fee2325cc9d.png)

**Comment by Djedouas** [comment]
Please see #35 

This is an ongoing issue which is being worked on

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas, I understand but I thought it was worthwhile highlighting when it happens so you can have data of the number of users that are affected and how often we cannot access the system.

Hope this helps,
Eduardo

**Comment by Djedouas** [comment]
You're right, it helps 👍🏼  

Please post a comment in the existing issue when it happens 😉
