### ISSUE TITLE
TOMS is very slow whilst logging in.

### ISSUE THREAD

**Issue by suhaibahmad97** [ProjectCentreLimited/TOMs#56]
![image](https://user-images.githubusercontent.com/117165256/200802041-674c77f9-e9f0-451c-b754-28d993cc22da.png)

I am able to log in, however TOMS does not seem to load for a long time, quite often being stuck around 12-20 % when loading Layer bays. 
I have tried different web browsers to log in and load TOMS and I have been unsuccessful.

Why is this issue occurring and what can be done to ensure this does not occur in the future ?

**Comment by Djedouas** [comment]
How long does it take to load? And does if fully load in the end or not?

**Comment by benoitdm-oslandia** [comment]
It seems to be linked to issue #35

**Comment by Djedouas** [comment]
> How long does it take to load? And does if fully load in the end or not?

I got no answer here, without answer, this issue will be closed soon.

**Comment by suhaibahmad97** [comment]
I have not used TOMS due to other project assignments.

If this issue occurs again, I will log this onto issue 35.

This issue can be resolved now. Thanks
