### ISSUE TITLE
Bay data info & Construction line

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#58]
Bay data information box doesn't have the option for 12-hour restriction which we need and when selecting the 'other' option it states 'please specify in notes' but here is no note box to add info to.

Construction line - this only works intermittently

**Comment by Djedouas** [comment]
@SeanC75 @Traffic-Orders where should be the "12-hour restriction" option?

If it's a needed option, I'm surprised that it has never been added in TOMs before.

Below is a screen capture of the bay form, so you can tell me where to put the option:

![image](https://user-images.githubusercontent.com/34267385/200872681-c6cc4ec9-61c3-4e82-84a2-bf198e208afa.png)

> Construction line - this only works intermittently

Can you be more precise? Is it reproducible? When it stops working, what do you do to make it work again?

**Comment by Traffic-Orders** [comment]
Hi Sean, the 12-hour restriction should be in the 'max stay' box.  We need this option when adding Electric Vehicle charging bays and we have an instruction at Director level to advertise this Order next week, so we need this issue resolved by tomorrow at latest please. Thanks

**Comment by SeanC75** [comment]
@Traffic-Orders just to clarify is this a new feature rather than something that is a bug with the current functionality?

**Comment by Traffic-Orders** [comment]
Sorry, forgot to answer your query re construction lines.  I can't really be more specific as it happens almost every time that I try to add a construction line.  It won't draw the line to the length I specify using line 'd' in the advanced digitising tool.  e.g. I select the 'create construction line' tool, then select the area on the map I want the line to start from, then enter the length under line 'd' in the advanced digitising tool but it just won't draw the line.  Its only worked for me a few times and more commonly won't work at all and my colleagues have had the same issue also.

**Comment by Traffic-Orders** [comment]
Hi Sean re the 'max stay' option for 12 hours - this will something new we need added to reflect the max stay for the EV charging bays.

**Comment by Djedouas** [comment]
> Hi Sean re the 'max stay' option for 12 hours - this will something new we need added to reflect the max stay for the EV charging bays.

So this is a new feature.

@SeanC75 This is typically the kind of minor addition that can be done directly by someone that has admin rights (the accounts with write_confirm_operator level). We will eventually organize a small training.

For today as it is an emergency I added this option.

The issue regarding the construction lines will be addressed in a dedicated issue.

**Comment by SeanC75** [comment]
@Traffic-Orders Please see the response above - re the 1hr option and the comment about the construction lines.
