### ISSUE TITLE
Bay data: PTA box must be editable for EV bays only

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#60]
Hi, we have another issue which we will need resolved by tomorrow please (as we have an instruction at Director level to advertise the associated Order next week).  When we are adding Electric Vehicle Charging bays to streets located within the Controlled Parking Zone, we need to be able to edit the 'PTA' box which currently defaults to the tariff for the relevant parking zone.  We are unable to do this currently as the 'PTA' box is greyed out and won't allow us to edit this.

**Comment by Djedouas** [comment]
Hi, I guess this is not specific to Electric Vehicle Charging bays, is it?

**Comment by Traffic-Orders** [comment]
Hi, as far as I understand it the issue at the moment is only specific to EV bays as other bay types e.g pay and display, should default to the tariff for the relevant parking zone.  This is not the case for EV bays, so we need to be able to edit the PTA box when adding/editing EV bays on TOMs.  Thanks

**Comment by Traffic-Orders** [comment]
Yes, this is specific to EV charging bays, whereby the parking tariff area should not default to that of the CPZ area.

Thanks
Sharon

**Comment by Djedouas** [comment]
This has been developed today, and will be available at next login.

**Comment by Djedouas** [comment]
Issue reopened.

Works on linux, does not work on Windows on existing bays.

@Traffic-Orders the feature partially works: if you create a new bay restriction, when you select EV bay in the restriction details you will be able to change the CPZ. I have to investigate why it does not work on existing restriction when changing the bay type.
