### ISSUE TITLE
Restrictions labels not clear on TOMs

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#63]
Hi, this is regards to the restrictions outside 101 Nicolson Street - there is a peak time loading/waiting restriction between 7.30am-9.30am and 4.00pm - 6.30pm (Mon-Fri).  

Parking is allowed between 9.30am - 4pm Mon-Fri and on a Saturday between 8am - 6.30pm.  

Currently these restriction times are not clear on TOMs and our Appeals team need to show this at cases gong to Tribunal.  

Can you therefore please amend this ASAP.

**Comment by Djedouas** [comment]
Hi,

I don't understand, is something missing somewhere?  
A choice in a drop-down menu maybe?

![image](https://user-images.githubusercontent.com/34267385/202484594-d6347113-d35b-47b9-908c-bdc485de6af8.png)

**Comment by Traffic-Orders** [comment]
Hi, it's the labels on the map that are not clear e.g., there only appears to be a label for the no waiting/no loading times and there doesn't appear to be a label showing the permitted parking times.  The appeals team need the map to show all the parking labels clearly.

**Comment by Traffic-Orders** [comment]
Central Zones operate Mon to Sat 8.30am to 6.30pm & Sun 12.30pm to 6.30pm
Peripheral Zones & Extended Zones operate Mon to Fri 8.30am to 5.30pm

**Comment by Traffic-Orders** [comment]
[Map Schedule Legend Template (005) as of 4.4.22.pdf](https://github.com/ProjectCentreLimited/TOMs/files/10084395/Map.Schedule.Legend.Template.005.as.of.4.4.22.pdf)

**Comment by Djedouas** [comment]
Hi,

Can you provide a screen capture of the location, please? I can't seem to find the missing labels around Nicolson street.

Also, the proposal number?

Thanks

**Comment by Traffic-Orders** [comment]
Hi, I have pasted below a screen shot of the location as requested:

![Nicolson St](https://user-images.githubusercontent.com/109733089/205345940-1b5213f2-d99f-440d-93c5-4c2457f9a0b3.JPG)

**Comment by Djedouas** [comment]
Thanks @Traffic-Orders 

I made some changes to label display, forcing all labels, even if there is label collision or superposition.

Hope it fixes the issue, it did on my tests.

I think that this was disabled because there is no tool yet to move labels, if they are colliding with other elements.

**Comment by Djedouas** [comment]
No update after 2 months, assuming fixed, closing.
