### ISSUE TITLE
Error message whilst creating proposal

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#67]
Hi,

Could the below please be looked at, myself (Isabelle Knops) and Darren Young are getting an error message, stopping us from creating a proposal:

![proposal](https://user-images.githubusercontent.com/109733089/204539485-54f5721f-f619-4b12-ad0e-67ae838c76a3.JPG)

Many thanks

**Comment by Djedouas** [comment]
Hi,

As far as I can see, there is no proposal title, which can cause this error.

**Comment by Traffic-Orders** [comment]
Hi,

I can confirm that we also tried entering the proposal title, but got the following error message:
![proposal 2](https://user-images.githubusercontent.com/109733089/204542449-6fe2b55f-4d61-4b3c-917d-c56a057d68e0.JPG)

**Comment by Djedouas** [comment]
This is really strange.

I checked everything I could and it seems that TOMs is doing something that it should not be able to do (actually it's trying to change attributes of proposal nb 0, rather than creating a new proposal...).

Can you (if not yet) log out and back in and try again please?

**Comment by Traffic-Orders** [comment]
Hi,

Tried logging in and out again, afraid the same error message appeared.

**Comment by Djedouas** [comment]
All right, I will investigate this ASAP.

In the meantime, it can be helpful to know if a person with the "WRITE (CAN CONFIRM)" rights can create a proposal.

**Comment by Traffic-Orders** [comment]
I can "write (can confirm)" but also get an error message when trying to create a proposal, see snippet below
![image](https://user-images.githubusercontent.com/109733089/204720165-14d6262a-f84b-4ce4-99b9-b4cc5bb5b649.png)
Thanks
Sharon

**Comment by Djedouas** [comment]
Hi,

I cleaned the attempts made yesterday.

It appears that a proposal with an empty title was existing (created yesterday, probably the first attempt). As a result, TOMs was in an unstable state because of this special proposal title (empty).

I removed this empty proposal, and the problem is now fixed on my side, can you try again please?

Thanks.

**Comment by SeanC75** [comment]
@Traffic-Orders Could you please try again based on the comment above?

**Comment by Traffic-Orders** [comment]
Hi,

Darren has given it a go and was able to create a new proposal, thank you :)
