### ISSUE TITLE
No sign in available

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#69]
![image](https://user-images.githubusercontent.com/109733089/205013287-185e035a-bb0d-463a-9f64-02a38cab38aa.png)
Hi, I have tried logging on to TOMs this morning and there is no sign in available using the link I have. Are you able to provide another link or is TOMs not online right now?

**Comment by Djedouas** [comment]
Everything is online, nothing changed.

Can you check with other users please?

Thanks

**Comment by SeanC75** [comment]
@Traffic-Orders can you confirm if this is still an issue please?

**Comment by Traffic-Orders** [comment]
Yes I can confirm that this is still an issue and others on the team are able to sign in.

**Comment by SeanC75** [comment]
@Traffic-Orders Is the URL in the screenshot the one you entered or did it re-direct to this page?

**Comment by Traffic-Orders** [comment]
There was no re-direct, this is the sign-in page I have saved and was able to use yesterday

**Comment by SeanC75** [comment]
@Traffic-Orders Would you mind trying this link please https://appstream2.eu-west-2.aws.amazon.com/#/streaming?reference=fleet%2FQgisCecFleet_App_LIVE

**Comment by Traffic-Orders** [comment]
Tries it and got a "404 page not found" message. However I tried my bookmarked page too and the login window now appears rather than just a blank page.

**Comment by SeanC75** [comment]
@Traffic-Orders OK thanks, so you have now managed to login?

**Comment by Traffic-Orders** [comment]
Yes all good thanks, it just finished loading.

**Comment by SeanC75** [comment]
Closing the issue.
