### ISSUE TITLE
fix TOMs login/access for Tom Mochan

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#71]
Hi my colleague Tom Mochan from the Parking Development team had access to TOMs but it has somehow been lost? His email address is tom.mochan@edinburgh.gov.uk can you please arrange for his login to be reinstated and reset his password? Many thanks

**Comment by benoitdm-oslandia** [comment]
Hi,
the account is still activated and I have not tool to reset its password. I will have to delete the account and recreate one.

Do have try with other passwords? What is the exact message? Can you post me a screenshot?

Regards.

**Comment by Traffic-Orders** [comment]
I have sent a copy of your message to Tom by email and await his response

**Comment by Traffic-Orders** [comment]
Or do you have an email address i can pass onto Tom for you to liaise directly with him to help identify the issue and resolve the matter

**Comment by benoitdm-oslandia** [comment]
Every one can create an account on GitHub and then post a new issue on TOMs or reply to an existing issue.

**Comment by Traffic-Orders** [comment]
Can you please delete the account and create a new one please for Tom Mochan

**Comment by benoitdm-oslandia** [comment]
The account has been deleted and a new one created. He will receive an email with the instructions. He MUST remember its password!

Regards.

**Comment by Traffic-Orders** [comment]
I received the following message by email from Tom, "Received two emails and they refer to installing the app on my desktop. The problem is I no longer have a desktop. I have an iPad and a laptop."
Can you please email Tom instructions how to install on his ipad and laptop?
Thanks
Sharon
