### ISSUE TITLE
Allanfield map tile

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#72]
Hi, I have noticed an anomaly with TOMs map tiles which I hope you can help with.  I created a proposal record (TRO/21/17) yesterday and was attempting to add a bay to the location under the proposal record, however I then noticed then when I toggle off the TOMs tab that there are bays already showing at the location (which are included in the proposal) but which I did not add to TOMs.  I am not sure how this has happened and wondered if this is something you can look into and advise who added the bays (and when) and if this will have any effect on the proposal once I add the relevant bays etc?  I have included a screen shot of the location (Allanfield) view when in the TOMs proposal record (TRO/21/17) and a screen show of the location when the TOMs tab is toggled off.

View of Allanfield when in proposal record TRO/21/17
![image](https://user-images.githubusercontent.com/109733089/206534186-316b8150-2177-4245-9cb7-e41621420b1c.png)

View of Allanfield when TOMs tab toggled off:
![image](https://user-images.githubusercontent.com/109733089/206534693-d8504318-f4a6-4818-846c-f3f516950c96.png)

**Comment by Djedouas** [comment]
Hi,

The bays belong to proposal **TEST -IK-CM-V1**, and were added between 13h50 and 13h58 by a user with WRITE permission but CAN'T CONFIRM (no more detail in TOMs history).

Therefore, they are not part of TRO/21/17 you are referring to (which I don't see in TOMs by the way).

**Comment by Djedouas** [comment]
No update after 2 months, closing.
