### ISSUE TITLE
Tom Mochan access, #71 still unresolved

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#75]
I received the following message by email from Tom, "Received two emails and they refer to installing the app on my desktop. The problem is I no longer have a desktop. I have an iPad and a laptop."
Can you please email Tom instructions how to install on his ipad and laptop?
Thanks
Sharon

**Comment by benoitdm-oslandia** [comment]
Hi Sharon, 

I am sorry but I have never heard such an issue and every one has already been able to login! This seems not an issue linked to the login to TOMs but more linked to the usage of its laptop and we are not mandated as an IT helpdesk. By the way, I think you (or maybe @SeanC75) are in the best position to help him with that.

Regards.

**Comment by Djedouas** [comment]
No update for 2 months, considering fixed, closing.
