### ISSUE TITLE
Removal of tile from a proposal

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#77]
Hi, can you please remove tile 1468 from proposal TRO/22/18.
A new Disabled Bay has been created OS 1 Marlborough Street on tile 1469 but there are no other changes heading west that should affect 1468, so not sure why it is included.
[Proposed Tile - APP 1-20 - 1469.pdf](https://github.com/ProjectCentreLimited/TOMs/files/10277821/Proposed.Tile.-.APP.1-20.-.1469.pdf)

**Comment by Djedouas** [comment]
Hi,

I can assure you that there is a change on tile 1468, see the screen captures below showing that a line overlapping on both tile 1468 and 1469 has been re-drawn:


![image](https://user-images.githubusercontent.com/34267385/208918207-433b7568-7cf0-475c-8cb4-25989979be1c.png)

![image](https://user-images.githubusercontent.com/34267385/208918393-369e5724-e045-4eb7-8e89-86e30c5bf63a.png)

The line is closer to the curb in TRO/22/18, and seems cleaner.

**Comment by Djedouas** [comment]
I can:

1/ Undo this change, so the tile won't be included anymore

2/ Leave it this way with two tiles in the proposal

3/ "Cheat" and change the old geometry with the clean geometry on the "No proposal" view, but this implies doing changes without opening or closing any proposal (administrator mode), so without history or archive

**Comment by Traffic-Orders** [comment]
Hi, option 1/ please , can you undo the change? I must have inadvertently brought the yellow line termination closer to the kerb when positioning the disabled bay.

**Comment by Djedouas** [comment]
Hi,

Done! No need to log out / log back in, just change the current proposal and go back to 22/15.
