### ISSUE TITLE
OS Data Update

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#78]
Hi, The base map needs to be updated at tile 1408 to include the new development at Adamslaw Place & Baileyfield Crescent. If this is not the way to get this done can you please advise who to contact. I have included a screenshot on TOMs and from our own Adopted Road Map, which does show the new development.
![OS Data Update - Tile 1408](https://user-images.githubusercontent.com/109733089/210055461-582a6b4e-bb27-4b0a-8469-57f7204f4903.jpg)
![Adopted Roads Map - Adamslaw Place   Baileyfield Crescent](https://user-images.githubusercontent.com/109733089/210055467-d4863183-021f-4b6f-a576-38488999e43c.jpg)

**Comment by Djedouas** [comment]
Hi,

Is there a public URL I can use to go to this Adopted Roads Map application?

**Comment by Traffic-Orders** [comment]
Hi,
I have only recently joined the team and do not yet have access to our GIS maps. The website for the Adopted Roads Map is below.
https://www.edinburgh.gov.uk/statutorypublicroads

**Comment by Djedouas** [comment]
OK.

To update TOMs I need the GIS file containing the data you want to add.

There is no workflow defined at the moment for this kind of request (data update), and I don't know where to find the data.

**Comment by Traffic-Orders** [comment]
I have been advised to obtain more up to date OS Data from our client, who raised the TRO request that involved this tile. Hopefully I will be able to pass something on fairly quickly.

**Comment by Traffic-Orders** [comment]
Would you be able to pull the OS Data from The City of Edinburgh Council Atlas, it's ArcGIS? This is showing Adamslaw Place as more up to date than Smallworld GIS.

[https://cityofedinburgh.maps.arcgis.com/apps/webappviewer/index.html?id=783e530d92994246bcaeb7419437fd78&showLayers=Atlas_6878_90]

**Comment by Djedouas** [comment]
What does OS mean?

Actually, we can't pull any data from this web address. There is no download link.

As I said before, we need the GIS file containing the data you want to add.

**Comment by greid12** [comment]
Just continuing this on from the email, i do not have the tool bar of editing i can only right click to toggle editing and have no function to edit the layers, just the bays etc.

![image](https://user-images.githubusercontent.com/116794639/217887238-b2e6572a-7c0a-40c7-bdba-7ec8ca8a4d7f.png)

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas - I would really appreciate if you could get back to Gavin as soon as possible. 
Many thanks
Eduardo

**Comment by Djedouas** [comment]
Hi @greid12  @EduardoMartin-Moral 

Let's continue in #92 so Traffic-Orders account is not polluted with our notifications.
