### ISSUE TITLE
New Account set up

### ISSUE THREAD

**Issue by greid12** [ProjectCentreLimited/TOMs#81]
Hi There,

Could i please request two new accounts to be set up.

Gordon Watson - email: Gordon.Watson1@projectcentre.co.uk
and 
Tululah Gordon-Hall - email: Tululah.Gordon-Hall@projectcentre.co.uk

Can they both have write but no approval permissions please.

Thanks,
Gavin

**Comment by benoitdm-oslandia** [comment]
I just added Gordon Watson. Tululah Gordon-Hall is already registered as a read only operator.

**Comment by greid12** [comment]
Is there a way to reset the account? Tululah has no way of accessing the old account set up and no emails on it

**Comment by benoitdm-oslandia** [comment]
I can resend the stask assignation email and if it does not work I will delete and recreate the account.
