### ISSUE TITLE
Trouble accessing TOMs

### ISSUE THREAD

**Issue by Djedouas** [ProjectCentreLimited/TOMs#84]
From @greid12 last week:

> I have checked with a colleague and all is working now thanks :)
> 
> I have trouble accessing TOMs do you know what this problem is related to? i cannot log in.
> 
> ![image](https://user-images.githubusercontent.com/116794639/213682983-11513af9-cf6d-4745-bb4f-4e840289767f.png)

From @greid12 today:

> This is still happening i am unable to get past the screen pictured above after closing browser, waiting time and clearing cache.
> 
> Is this a connection problem for myself?
> 
> Thanks

**Comment by Djedouas** [comment]
@benoitdm-oslandia any idea other than changing browser, cleaning cache, etc?

It seems to be a AWS problem...

**Comment by benoitdm-oslandia** [comment]
I'll have a look asap

**Comment by benoitdm-oslandia** [comment]
Hi @greid12! 

I saw no issues in the appstream sessions of the 20th. 

As @Djedouas suggested, have you try since with another web browser or maybe by using a private navigation tab?

**Comment by greid12** [comment]
Our company has restrictions so we can only use Microsoft edge as a browser. We recently updated the system and since then it has been a problem. I will continue to investigate. Thanks

**Comment by benoitdm-oslandia** [comment]
It looks like a script blocker or some kind of filtering... Have you sent this issue to your IT?

**Comment by greid12** [comment]
Yeah i have contacted our IT and awaiting a response from them, hopefully able to resolve it soon

**Comment by greid12** [comment]
Apologies for all the comments. Our IT engineers cannot seem to resolve the issue. Dan Ursell has sent an email regarding this, is there any further update on what may be the problem?

**Comment by benoitdm-oslandia** [comment]
Hi gavin,

I impersonnated your role to check if there was issues with your account but I am able to connect without any issues. May be there is a pbm with the connection url you are using, I will send you a new invitation email soon.

Regards.

**Comment by benoitdm-oslandia** [comment]
It look like your IT has been able to login with the impersonated link. Could you retry @greid12 with your normal link?

**Comment by greid12** [comment]
No the original link does not work still. Is there a way to reissue the web address?

**Comment by benoitdm-oslandia** [comment]
I can delete your account and create a new one hoping it will change the url but I won't be able to do more.

**Comment by benoitdm-oslandia** [comment]
You should have received new email/url/passwd. Let me know!

**Comment by greid12** [comment]
Hi Benoit, that has worked!! thank you very much

**Comment by benoitdm-oslandia** [comment]
oh great! I did not believe it could work!

I close this issue!
