### ISSUE TITLE
Adding the vector editing tabs

### ISSUE THREAD

**Issue by greid12** [ProjectCentreLimited/TOMs#85]
![image](https://user-images.githubusercontent.com/116794639/214820169-65a6e882-a3ef-49d0-8a7e-1264e547feeb.png)

Hi, is it possible to get the vector editing tools added into the TOMs account. It is a service we provide the client and cannot preform it without the geoprocessing tools.

Even just on the write confirm accounts would be perfect.

Thanks

**Comment by Djedouas** [comment]
Hi,

Ok for adding this to the write confirm accounts. What do you do with these tools for example?

**Comment by Djedouas** [comment]
Vector Menu added. 

What are your needs with this menu?

**Comment by greid12** [comment]
Hi, we perform OS base map updates for the client. We need to alter the mask layers and OS layers which requires adding in new vectors. It was something we were told fell under the consultation side of our agreement.

**Comment by Djedouas** [comment]
Ok I see.

Is it related to #78 ?
