### ISSUE TITLE
Error when attempting to confirm a proposal 

### ISSUE THREAD

**Issue by SeanC75** [ProjectCentreLimited/TOMs#87]
Long story short, they are attempting to confirm/accept a proposal in TOMS (TRO-21-03B Zone N8) and are being met with the following error messages: 
 
![image](https://user-images.githubusercontent.com/115094257/215821446-18b72e8a-a253-4216-ade6-4ac0a97ef978.png)

 
![image](https://user-images.githubusercontent.com/115094257/215821490-84e531e3-b8da-4ca7-85bb-81ee7550f261.png)

Given the scheduled advertising date of this Friday (February 3rd), it is critical that this issue is resolved by COP today and the proposal confirmed.

**Comment by Djedouas** [comment]
I reproduced the problem.

Note for later, need to discuss with @benoitdm-oslandia to understand what's going on...

On restriction `00249bb5-4c0a-4b89-b336-a58ba59511e9` in layer `Bays` (maybe not the only feature...) we can't modify attributes, even in QGIS attribute table, we have this error:

>2023-01-31 17:43:47.242 UTC [3102199] toms_admin@toms ERROR:  canceling statement due to statement timeout
> 2023-01-31 17:43:47.242 UTC [3102199] toms_admin@toms CONTEXT:  while locking tuple (64,18) in relation "Bays"
> 2023-01-31 17:43:47.242 UTC [3102199] toms_admin@toms STATEMENT:  UPDATE "toms"."Bays" SET "OpenDate"='2023-02-01' WHERE "RestrictionID"::text='00249bb5-4c0a-4b89-b336-a58ba59511e9'

**Comment by Traffic-Orders** [comment]
Please note this Order needs confirmed asap with an effective date of 6 Feb 2023 so we are hoping this can be sorted early this morning

**Comment by Djedouas** [comment]
The bug from yesterday is fixed, but there is another problem:

Some tiles have a revision date > 6 Feb 2023 which causes a synchronization error:

![image](https://user-images.githubusercontent.com/34267385/216016780-56b7ee15-905b-4aae-8fc7-76d0b7aa1185.png)

For example, tile 749 has a revision date of 13 Feb 2023.

Do you know where it is coming from and / or how to resolve this? I don't know the process well enough, big lack of documentation. (I don't even know why it's a problem, and where this 13 Feb 2023 date comes from).

**Comment by SeanC75** [comment]
@Traffic-Orders Could you take a look at the comment above?

**Comment by Traffic-Orders** [comment]
we have changed the coming into effect date for 14/2/2023 for Zone N8. I have also successfully confirmed the order on TOMs for that date

**Comment by Djedouas** [comment]
Great!

Glad to hear it.

Closing the issue.
