### ISSUE TITLE
Tiles revision

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#89]
Hi,

We had a meeting with @Traffic-Orders yesterday and we would appreciate if the Tile Revision Numbers for the tiles listed in the attached spreadsheet are revised to those included in Column F 'Agreed solution'.
[Copy of Copy of Copy of Copy of Copy of Tile revison No. V05 FINAL VERSION PCL comments01022023.xlsx](https://github.com/ProjectCentreLimited/TOMs/files/10566696/Copy.of.Copy.of.Copy.of.Copy.of.Copy.of.Tile.revison.No.V05.FINAL.VERSION.PCL.comments01022023.xlsx)

I would really appreciate if you could give indicative timescales for the completion of this task.

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

Thanks for the spreadsheet, that made the work much more easy and straightforward.

Task completed.

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas,

I have completed a spot check (10tiles) and the following tiles did not have the right revision numbers to match Column F 'Agreed solution':
661, 853, 1015, 1395, 1684 and 3378.

Can you please double check the rev numbers for all the tiles that were to be revised and amend to the right ones?

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Where and how do you check the revision number?

Example of how I see the revision number:

![image](https://user-images.githubusercontent.com/34267385/216295903-1e9c5cbd-383e-4a1b-a745-caaca7086eb3.png)

**Comment by EduardoMartin-Moral** [comment]
Hi,

I print the tile from the '0-No proposal shown' proposal and check the drawing frame box.
Example of what I see for Tile 1015:

![image](https://user-images.githubusercontent.com/117166421/216296854-75d89aaa-c5ef-4fb3-bf34-05a4f811b172.png)

**Comment by Djedouas** [comment]
OK.

You have to know that the revision number on the PDF is the number the tile **will have** once the proposal is confirmed.

So when the print tool generates the PDF:
- if the proposal is not confirmed yet, the revision number is increased by 1, temporarily, only for this PDF file, not in the database
- if the proposal is confirmed, the revision number has been increased by the confirmation process, so the real revision number in the database is used

So now, all the tiles in the xls file I changed have the revision number requested in the database.

Does this new information about this behavior change the revision numbers you have requested?

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas 

The PDFs I have generated are from the '0-No proposal shown' proposal (i.e. current restrictions). 

I understand that all the tiles in the '0-No proposal shown' proposal are 'Confirmed' and the revision numbers shown when printing should match the 'real revision number'. Therefore those in the spreadsheet.

Then, I understand that if I would be printing from a proposal other than '0-No proposal shown' and a change in the restrictions of that tile has been implemented as part of this new proposal, the tile would be 'Not Confirmed' and the revision number would provisionally be 'real revision number +1'.

I do not understand why the revision numbers on the PDFs exported from the '0-No proposal shown' if they are 'Confirmed' do not match the 'real revision numbers'.

I am happy to arrange a call over Team to discuss if that helps.
Thanks for your help :)

**Comment by Djedouas** [comment]
Oh right! I focused on the revision number, but I see the "CONFIRMED" status on your screen capture.

I have to do a deeper code investigation.

**Comment by Djedouas** [comment]
In the database there is the history for a given tile, which proposal updated the revision number.

In fact I need to delete the association between a proposal and a tile to decrese the tile revision number.

For revisions going from 1 to 0 it's easy, I have to delete the only association proposal-tile that exists.

For the other tiles, I need you to tell me which proposal I have to de-associate from the tile.

I will provide you a list to choose from next week.

**Comment by Djedouas** [comment]
It seems that there is no tile with revision number = 0 in the database... can you confirm that?

It seems that revision numbers are starting at 1.

For revisions which are missing a proposal (from a lower to a higher revision) I will need the proposal name. I think there is some information in the xls file. Can I rely on this?

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas ,

What about tiles such as 2989, 2990, 2991...? Aren't they Rev 0 in the database?
These tiles have not gone through any proposal that is why they do not print when selecting the '0-No proposal shown' proposal. I would imagine these tiles to currently be Rev 0.

For revisions which are missing a proposal - can you please extract a report? I will check with @Traffic-Orders.

Regards,
Eduardo

**Comment by Djedouas** [comment]
> What about tiles such as 2989, 2990, 2991...? Aren't they Rev 0 in the database?
These tiles have not gone through any proposal that is why they do not print when selecting the '0-No proposal shown' proposal. I would imagine these tiles to currently be Rev 0.

Thanks for the tile number examples :) those tiles do not have any revision number (not even 0).

Working on the extract.

**Comment by Djedouas** [comment]
[Here is the extract](https://github.com/ProjectCentreLimited/TOMs/files/10578565/report.ods)

For me, there is a misbehavior of TOMs somewhere, because lots of the bad revision numbers are 1 too high, because the tile has been associated with the proposal "0 - No proposal shown", which is absurd (in my understanding).

So I decided to make a test in my local TOMs:
- create a new proposal
- draw a bay in a tile with no history (2990)
- accept the proposal

And the tile has been associated a revision number 1 with this new proposal (and no association with the proposal 0).

That's why I now think that every association with the proposal 0 and a revision increase is an error (please confirm, or infirm?). We need to find a way to reproduce the error though, to understand it.

In the report are my suggestions to resolve the conflicts.

We can schedule a meeting if you want (I will be available starting on 14th Feb and the following days of this week).

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas ,

I agree - those tiles for which their 'proposals history' is only associated with proposal '0 - No proposal shown' should be Rev0 and not Rev1 as you suggest in your extract.
I will use your extract to inform @Traffic-Oders and get back to you with a revised extract clarifying the action/s to be taken.

Thanks,
Eduardo

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas,

I had a meeting with @Traffic-Orders yesterday and we agreed the revision numbers and tile history as per the attached spreadsheet.

Please make sure the changes are completed **NOT BEFORE** the 14th of February. Thus, completing these changes **ON** the 15th February would be ideal.

Please do not hesitate to contact me if you have any questions. Happy to discuss over Teams if required.

Many thanks,
Eduardo 


[tiles 20230208.ods](https://github.com/ProjectCentreLimited/TOMs/files/10699487/tiles.20230208.ods)

**Comment by Djedouas** [comment]
All right, the spreadsheet is quite clear, I schedule this for the 15th February.

Thanks.

**Comment by Djedouas** [comment]
Hi @EduardoMartin-Moral 

Working on it, there is maybe a missing action for tile 745 in the spreadsheet:

![image](https://user-images.githubusercontent.com/34267385/218990738-2c850164-f679-4544-af6a-d0e2700acbc8.png)

Should I make it Rev0 or should I make it Rev1 with TRO-18-79?

Thanks

**Comment by Djedouas** [comment]
For tile 422: should I make it Rev0?

**Comment by EduardoMartin-Moral** [comment]
@Djedouas could I ask you to gather all the queries in the spreadsheet once you complete the first sweep?

I don't want to miss any of your questions.

thanks,
Eduardo

**Comment by Djedouas** [comment]
First sweep completed.

Here is a screenshot of where I have doubts:

![image](https://user-images.githubusercontent.com/34267385/219017180-9853c793-3950-4653-ad0f-27ccda84fe88.png)

I guess that:
- 745 should be Rev1 with TRO-18-79
- 911, 964, 972 should be Rev0
- 422 should be Rev0 also, or a proposal is missing

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas 

Tile 745:
Rev0 - '0-no proposal shown'
Rev 1 - TRO-18-79

Tiles 911. 964 and 972:
Rev0 - '0-no proposal shown'

Tile 422: 
Rev 1- '0-no proposal shown' (yes - Rev1 to confirm)

thanks,
Eduardo

**Comment by Djedouas** [comment]
The requested changes have been made today, tested on the staging version, confirmed visually on a subset, and made live.

Waiting for your feedback.

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas 

Can you please add the TROs in the tiles' history as per the orange cells below:
![image](https://user-images.githubusercontent.com/117166421/219351469-0dd0e7a6-22f1-4e8d-b5f3-22c67aa219b1.png)


Many thanks
Eduardo

**Comment by Djedouas** [comment]
Done, can you confirm?

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas  - ticket closed

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas 

@Traffic-Orders have noticed a potential issue with map tile 1746.

Could you please confirm the number of Revs carried out to the map tile, the associated Orders and effective dates?

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi @EduardoMartin-Moral 

Here is tile 1746 history:

| ProposalID | TileNr | RevisionNr |  ProposalCreateDate | ProposalNotes |  ProposalTitle     | ProposalOpenDate 
| ------------ | -------- | ------------ | ------------------ | ---------------------- | --------- | ---------
|          0 |   1746 |          1 |         2018-10-15         |               | 0 - No Proposal shown | 2018-10-15
|         48 |   1746 |          2 |         2019-07-31         |               | TRO-18-70             | 2019-10-01
|         87 |   1746 |          3 |        2019-08-16         | CPZ Areas     | TRO-19-04             | 2019-10-07
|        164 |   1746 |          4 |    2020-04-14         | TRO-20-16     | TRO-20-16             | 2022-02-01
|        236 |   1746 |          5 |     2021-11-03         |               | TRO-21-25             | 2023-01-30
|          4 |   1746 |          6 |    2021-04-23         |               | TRO-21-03B Zone S5    | 2023-02-06

**Comment by EduardoMartin-Moral** [comment]
Confirmation received from @Traffic-orders to proceed with the closure of the ticket.
