### ISSUE TITLE
Map tile printing causes TOM to crash

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#91]
Hi,

Just to make you aware that TOMs crashes for two users (so far) when trying to print map tiles:

![TOM crash](https://user-images.githubusercontent.com/109733089/217286903-6d22fc21-e76f-4367-b889-68fb23376093.JPG)

**Comment by Traffic-Orders** [comment]
Hi,

Forgot to mention that we have work that relies on this being fixed quickly.

Many thanks in advance

**Comment by Djedouas** [comment]
Should be ok now, after a logout/login, can you confirm?
