### ISSUE TITLE
Updating the OS map system

### ISSUE THREAD

**Issue by Djedouas** [ProjectCentreLimited/TOMs#92]
Request from @greid12 

> We provide a service for the client, Edinburgh, where they require the OS map updated as they have redetermined the use of the area. This can include adding bike lanes or narrowing/extending kerb lines. This was part of the reason why I requested a vector editing tab.
> 
> I am struggling a little bit to relearn the new method on the new system, a lot are transferable however I thought I would email so I can explain what is to be done and hopefully you can understand and point me in the right direction on the new system.
> 
> We initially create shapefiles on QGIS before TOMs and load the layers in and trim and edit the vectors before assigning them to current layers within the system. To begin we need the files from the browser tab and finding them and adding them to the layers tab. This part seems to be the first hurdle and I cannot understand how to add these shapefiles in. From this I would edit one of the shapefiles and assign a new buffer vector to this, this acts as the ‘mask layer’ and can be copied into one of the existing layer through the attribute tables. The next is to edit the proposed kerb line which we are changing and that involves using the splitting tools form QGIS (which do not appear to be on TOMs currently). After this they are copied into the correct layer through attribute tables, to make them appear on the correct proposal we assign a proposal ID number and they appear in the proposal and not on every layer/proposal. There was a final step Tim did from MHTC however hopefully that is not needed with all our accounts having correct access.
> 
> Any questions on this let me know as I am unable to manoeuvre the system as easily.
> 
> Regards,

**Comment by Djedouas** [comment]
Hi @greid12 ,

I understand that you need to be able to load external shapefiles into TOMs.

## In TOMs staging version

To do this, it seems that the browser panel is of no use (apparently permissions issues with AWS system because I can't see any file I upload), so I removed it.

So I enabled the Data Source Manager button

![image](https://user-images.githubusercontent.com/34267385/217791541-053cb382-0abe-4e52-9a32-2004b1da0eab.png)

The process to load an external shapefile into TOMs, for you to test, is:

### 1/ upload your shapefile (all files, .shp, .shx, etc.) to AWS

![image](https://user-images.githubusercontent.com/34267385/217792321-320017fe-f7e7-4e0f-a95d-54705252642b.png)

![image](https://user-images.githubusercontent.com/34267385/217792385-88ed60cf-bb03-42e7-b1d7-ed0aa4eb10b3.png)

### 2/ add it with the data source manager

![image](https://user-images.githubusercontent.com/34267385/217792833-626b0105-b6ba-4d9c-b287-0e50c2f46fc6.png)

---

I am waiting for your feedback on this.

**Comment by Djedouas** [comment]
@greid12 of course you don't have the edition toolbar, you have to go on the **staging** version of TOMs, where we will do our tests, before we move any change to the live version now.

**Comment by greid12** [comment]
Hi, i have made changes to a proposal on the Staging site. TRO/21/32. I have updated a kerbline, what is the process now for changing this over to the live system? Thanks

**Comment by Djedouas** [comment]
We are defining the new process together, now, actually 😄 

Do you want the changes to appear on all the proposals, or is it ok that it's only up-to-date in this TRO/21/32?

**Comment by greid12** [comment]
If you could just update it in TRO/21/32.

**Comment by greid12** [comment]
When the file is approved by the client, the version numbers will increase (as expected) however they requested the removal of a tile which had changes made, this is tile 1396. i imagine even though we removed the kerbline update from this the restriction ID's etc will have changed as we needed to add new restrictions. No fault of TOMs or our own just an unfortunate late change

**Comment by EduardoMartin-Moral** [comment]
@Djedouas just to add to @greid12 's comment.

When printing TRO/21/32 Tile 1396 should not be included. Therefore, please remove TRO/21/32 from Tile 1396 history.
Thanks,
Eduardo

**Comment by greid12** [comment]
I have a question about the OS updates
![image](https://user-images.githubusercontent.com/116794639/218757519-2734a104-c6e0-4f80-8945-f0664a272d92.png)

When converting a shapefile to a buffer (we do this process so it acts as the mask for the kerb lines) it does not appear. You can see in the red circle i have made it bright green but nothing is appearing on the street. Is there a reason for this?

**Comment by greid12** [comment]
There are some other technical issues, for example when copying the proposed kerb lines over to assign them to the correct proposal, ensuring they show up. We copy the properties from the attribute table to the mapping updates and normally this is okay. This time i get met with an error message

**Comment by greid12** [comment]
i appreciate this all may be abit new to you as it is all in the TOMs system. Happy to organise a call in the next few days to discuss if it is easier

**Comment by EduardoMartin-Moral** [comment]
Morning @Djedouas , can you please share your availability with @greid12 for a call via Teams this week?

Thanks,
Eduardo

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas ,

Can you please give us an update on TRO/21/32?

- Has it been made live?
- Has TRO/21/32 been removed from Tile 1396 history?
- When printing TRO/21/32 can you please confirm Tile 1396 is not included?

Many thanks,
Eduardo

**Comment by Djedouas** [comment]
Hi,

> Has it been made live?

No, I think I need to understand the process better, and will contact @greid12 by email to arrange a call.

If it's urgent, perhaps @greid12 you can do the same steps that you did on the staging version, on the live version (tell me if you do this so I add the toolbar in the live version).

> Has TRO/21/32 been removed from Tile 1396 history?

They have not been associated yet so it's ok (the proposal has not been confirmed).

> When printing TRO/21/32 can you please confirm Tile 1396 is not included?

I understand that I can remove everything drawn in this tile for this TRO (that is to say some lines and some bays), is it correct?

**Comment by Djedouas** [comment]
Hi,

Every change in tile 1396 in TRO-21-32 has been reverted, so this tile does not appear anymore when printing.

OS map updates, following our call this morning, have been made completely, on the live version.

I adjusted other technical layers for the changes to appear only in the proposal, and not on "No proposal shown".

@greid12 Can you confirm? If it's ok you can close the issue.

PS: @greid12 the staging version is now correctly pointing on the staging database.
