### ISSUE TITLE
TOMS not creating yellow lines

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#94]
Hi, I have been trying to plot restrictions on TOMs today and, whilst it allows me to insert a bay it will not allow me to plot yellow lines.  My colleague has tried this also and has the same issue.  For ref the proposal I was working on was TRO/22/17.  Can this issue please be resolved ASAP and could you also check that all other plotting functions are operational so that we can continue to draft.

**Comment by Djedouas** [comment]
Hi,

Sorry for the regression, and the inconvenience caused.

This should be fixed now, a log out/log in is required.
