### ISSUE TITLE
New user

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#95]
Hi,

Could stuart.tervet@edinburgh.gov.uk please be set up as a new read-only user?

Many thanks

**Comment by benoitdm-oslandia** [comment]
Hi! What kind of permission do you want for this user?

**Comment by Traffic-Orders** [comment]
Hi,

As per the request, please make the user read-only :)

**Comment by benoitdm-oslandia** [comment]
ok sorry... it is monday!

**Comment by benoitdm-oslandia** [comment]
There will be a delay as we have reached the user limit. I will create an increase request to AWS support and it could take a week before it is effective.

ping @Djedouas

**Comment by Traffic-Orders** [comment]
Thank you :)

**Comment by benoitdm-oslandia** [comment]
quota has been increased, so I added the user!
