### ISSUE TITLE
New Toms Accounts for CEC

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#98]
Hi,
Could I please request two new accounts to be set up.

- Rurigdh McMeddes - Rurigdh.McMeddes@edinburgh.gov.uk
- Douglas Grant - Douglas.Grant@edinburgh.gov.uk

Can they have read-only permissions please?
Many thanks,
Eduardo

**Comment by Djedouas** [comment]
@benoitdm-oslandia ok to go

**Comment by benoitdm-oslandia** [comment]
done!
