### ISSUE TITLE
New account for CEC - Maria Pueyo

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#99]
Hi,

Could I please request one new account to be set up.

Maria Pueyo <Maria.Pueyo@edinburgh.gov.uk>

Can it have write but no approval permissions please?
Many thanks,
Eduardo

**Comment by Djedouas** [comment]
@benoitdm-oslandia ok to go

**Comment by benoitdm-oslandia** [comment]
done!
